/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GraphicInterfaces;

import Main.Movie;
import Main.Session;
import Utilities.ReserchUtilities;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javafx.util.Pair;
import javax.swing.ListSelectionModel;
import javax.swing.RowSorter;
import javax.swing.SortOrder;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Icaro
 */
public class MovieWindowPanel extends javax.swing.JFrame {

    Integer idMovie;

    boolean editMode;

    /**
     * Creates new form MovieWindowPanel
     */
    public MovieWindowPanel() {
        editMode = false;
        initComponents();
        buttonDelete.setVisible(false);
        tableSessions.setRowSelectionAllowed(true);
        tableSessions.setSelectionMode(ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
        fillTable(ReserchUtilities.findAllSessions(), null);
    }

    public MovieWindowPanel(Movie movie) {
        editMode = true;
        idMovie = movie.getId();
        initComponents();
        textAreaSynopsis.setText(movie.getSynopsis());
        textFieldDataFinal.setText(movie.getInTheatersPeriod().getValue());
        textFieldDataInicio.setText(movie.getInTheatersPeriod().getKey());
        textFieldLanguage.setText(movie.getLanguage());
        textFieldName.setText(movie.getName());
        textFieldTime.setText(String.valueOf(movie.getTime()));
        comboBoxAgeRating.setSelectedItem(movie.getAgeRating());
        comboBoxGenre.setSelectedItem(movie.getGenre());
        comboBoxInTheater.setSelectedItem(movie.isInTheaters() == true
                ? "Sim" : "Não");
        tableSessions.setRowSelectionAllowed(true);
        tableSessions.setSelectionMode(ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
        fillTable(ReserchUtilities.findAllSessions(), movie.getSessions());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelName = new javax.swing.JLabel();
        textFieldName = new javax.swing.JTextField();
        labelInTheater = new javax.swing.JLabel();
        comboBoxInTheater = new javax.swing.JComboBox<>();
        labelDataInicio = new javax.swing.JLabel();
        labelDataFinal = new javax.swing.JLabel();
        textFieldDataInicio = new javax.swing.JTextField();
        try{ 
            javax.swing.text.MaskFormatter mask= new javax.swing.text.MaskFormatter("####/##/##");
            textFieldDataInicio = new javax.swing.JFormattedTextField(mask);
        }
        catch (Exception e){
        }
        textFieldDataFinal = new javax.swing.JTextField();
        try{ 
            javax.swing.text.MaskFormatter mask= new javax.swing.text.MaskFormatter("####/##/##");
            textFieldDataFinal = new javax.swing.JFormattedTextField(mask);
        }
        catch (Exception e){
        }
        labelAgeRating = new javax.swing.JLabel();
        comboBoxAgeRating = new javax.swing.JComboBox<>();
        labelLanguage = new javax.swing.JLabel();
        textFieldLanguage = new javax.swing.JTextField();
        labelGenre = new javax.swing.JLabel();
        comboBoxGenre = new javax.swing.JComboBox<>();
        labelTime = new javax.swing.JLabel();
        textFieldTime = new javax.swing.JTextField();
        labelSynopsis = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textAreaSynopsis = new javax.swing.JTextArea();
        buttonSave = new javax.swing.JButton();
        buttonDelete = new javax.swing.JButton();
        buttonCancel = new javax.swing.JButton();
        labelSession = new javax.swing.JLabel();
        labelSessionHint = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableSessions = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        labelName.setText("Nome:");

        labelInTheater.setText("Em Cartaz: ");

        comboBoxInTheater.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sim", "Não" }));

        labelDataInicio.setText("Data Inicial de Exibição:");

        labelDataFinal.setText("Data Final de Exibição:");

        textFieldDataInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldDataInicioActionPerformed(evt);
            }
        });

        labelAgeRating.setText("Classificação:");

        comboBoxAgeRating.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Livre", "10", "12", "14", "16", "18" }));

        labelLanguage.setText("Idioma:");

        labelGenre.setText("Gênero:");

        comboBoxGenre.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ação", "Terror", "Romance", "Suspense", "Comédia", "Drama", "Ficção", "Aventura" }));

        labelTime.setText("Duração:");

        labelSynopsis.setText("Sinopse:");

        textAreaSynopsis.setColumns(20);
        textAreaSynopsis.setLineWrap(true);
        textAreaSynopsis.setRows(5);
        jScrollPane1.setViewportView(textAreaSynopsis);

        buttonSave.setText("Salvar");
        buttonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSaveActionPerformed(evt);
            }
        });

        buttonDelete.setText("Excluir");
        buttonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDeleteActionPerformed(evt);
            }
        });

        buttonCancel.setText("Cancelar");
        buttonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCancelActionPerformed(evt);
            }
        });

        labelSession.setText("Sessões:");

        labelSessionHint.setFont(labelSessionHint.getFont().deriveFont((labelSessionHint.getFont().getStyle() | java.awt.Font.ITALIC) & ~java.awt.Font.BOLD, 11));
        labelSessionHint.setForeground(new java.awt.Color(153, 153, 153));
        labelSessionHint.setText("Manter Selecionadas as Sessões desejadas");

        tableSessions.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Ativa no Filme", "Horario", "Sala"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tableSessions);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelName)
                                .addGap(18, 18, 18)
                                .addComponent(textFieldName))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelInTheater)
                                .addGap(18, 18, 18)
                                .addComponent(comboBoxInTheater, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(labelAgeRating)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(comboBoxAgeRating, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(labelSynopsis)
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelDataInicio)
                                    .addComponent(labelDataFinal))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textFieldDataInicio)
                                    .addComponent(textFieldDataFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelGenre)
                                .addGap(18, 18, 18)
                                .addComponent(comboBoxGenre, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelLanguage)
                                .addGap(18, 18, 18)
                                .addComponent(textFieldLanguage, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(labelTime)
                                .addGap(18, 18, 18)
                                .addComponent(textFieldTime))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelSession)
                                .addGap(18, 18, 18)
                                .addComponent(labelSessionHint)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(buttonSave)
                        .addGap(18, 18, 18)
                        .addComponent(buttonDelete)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buttonCancel))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelName)
                    .addComponent(textFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelInTheater)
                    .addComponent(comboBoxInTheater, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelAgeRating)
                    .addComponent(comboBoxAgeRating, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelDataInicio)
                    .addComponent(textFieldDataInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelDataFinal)
                    .addComponent(textFieldDataFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelLanguage)
                    .addComponent(textFieldLanguage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelTime)
                    .addComponent(textFieldTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelGenre)
                    .addComponent(comboBoxGenre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(labelSynopsis)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelSession)
                    .addComponent(labelSessionHint))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonSave)
                    .addComponent(buttonDelete)
                    .addComponent(buttonCancel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSaveActionPerformed
        Movie movie = new Movie();
        movie.setAgeRating(comboBoxAgeRating.getSelectedItem().toString());
        movie.setGenre(comboBoxGenre.getSelectedItem().toString());
        movie.setInTheaters(comboBoxInTheater.getSelectedItem().toString().equals("Sim"));
        movie.setInTheatersPeriod(new Pair<>(textFieldDataInicio.getText(), textFieldDataFinal.getText()));
        movie.setLanguage(textFieldLanguage.getText());
        movie.setName(textFieldName.getText());
        movie.setSessions(null);
        movie.setSynopsis(textAreaSynopsis.getText());
        movie.setTime(Integer.valueOf(textFieldTime.getText()));

        final int[] selectedRows = tableSessions.getSelectedRows();
        List<Session> movieSessions = new ArrayList<>();

        if (selectedRows.length > 0) {
            for (int row : selectedRows) {
                movieSessions.add(ReserchUtilities.findSessionByParams(
                        tableSessions.getValueAt(row, 1).toString(),
                        ReserchUtilities.findRoomByNumber(
                                (Integer) tableSessions.getValueAt(row, 2)).getId()));
            }
        }

        movie.setSessions(movieSessions.size() > 0 ? movieSessions : null);

        if (editMode) {
            movie.setId(idMovie);
            if (movie.editMovie(movie)) {
                this.setVisible(false);
            }
        } else {
            if (movie.insertMovie(movie)) {
                this.setVisible(false);
            }
        }
    }//GEN-LAST:event_buttonSaveActionPerformed

    private void buttonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDeleteActionPerformed
        if (new Movie().deleteMovie(idMovie)) {
            this.setVisible(false);
        }
    }//GEN-LAST:event_buttonDeleteActionPerformed

    private void buttonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_buttonCancelActionPerformed

    private void textFieldDataInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldDataInicioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldDataInicioActionPerformed

    private void fillTable(List<Session> sessions, List<Session> activatedSessions) {

        DefaultTableModel defaultTableModel = (DefaultTableModel) tableSessions.getModel();

        while (tableSessions.getRowCount() > 0) {
            defaultTableModel.removeRow(0);
        }

        Set<Integer> activatedSessionsIds = new HashSet<>();

        if (activatedSessions != null) {
            activatedSessions.forEach(e -> activatedSessionsIds.add(e.getId()));
        }

        for (Session session : sessions) {

            Object row[] = new Object[3];

            if (activatedSessionsIds.contains(session.getId())) {
                row[0] = "Sim";
            } else {
                row[0] = "Não";
            }

            row[1] = session.getTime();
            row[2] = session.getRoom().getNumber();

            defaultTableModel.addRow(row);
        }
        TableRowSorter<TableModel> sorter
                = new TableRowSorter<>(tableSessions.getModel());
        tableSessions.setRowSorter(sorter);

        List<RowSorter.SortKey> sortKeys = new ArrayList<>(25);
        sortKeys.add(new RowSorter.SortKey(0, SortOrder.DESCENDING));
        sorter.setSortKeys(sortKeys);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MovieWindowPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MovieWindowPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MovieWindowPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MovieWindowPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MovieWindowPanel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCancel;
    private javax.swing.JButton buttonDelete;
    private javax.swing.JButton buttonSave;
    private javax.swing.JComboBox<String> comboBoxAgeRating;
    private javax.swing.JComboBox<String> comboBoxGenre;
    private javax.swing.JComboBox<String> comboBoxInTheater;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel labelAgeRating;
    private javax.swing.JLabel labelDataFinal;
    private javax.swing.JLabel labelDataInicio;
    private javax.swing.JLabel labelGenre;
    private javax.swing.JLabel labelInTheater;
    private javax.swing.JLabel labelLanguage;
    private javax.swing.JLabel labelName;
    private javax.swing.JLabel labelSession;
    private javax.swing.JLabel labelSessionHint;
    private javax.swing.JLabel labelSynopsis;
    private javax.swing.JLabel labelTime;
    private javax.swing.JTable tableSessions;
    private javax.swing.JTextArea textAreaSynopsis;
    private javax.swing.JTextField textFieldDataFinal;
    private javax.swing.JTextField textFieldDataInicio;
    private javax.swing.JTextField textFieldLanguage;
    private javax.swing.JTextField textFieldName;
    private javax.swing.JTextField textFieldTime;
    // End of variables declaration//GEN-END:variables
}
