/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GraphicInterfaces;

import Main.Movie;
import Main.Sale;
import Main.Ticket;
import Utilities.ReserchUtilities;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.stream.Collectors;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Icaro
 */
public class SaleListing extends javax.swing.JFrame {

    /**
     * Creates new form SaleListing
     */
    public SaleListing() {
        initComponents();
        fillTable(ReserchUtilities.findSalesByParams(new ArrayList<>(), null, null, null, null));
        LocalDate date = LocalDate.now().minusDays(30);
        spinnerInitialDate.setValue(Date.from(date.atStartOfDay
        (ZoneId.systemDefault()).toInstant()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFormattedTextField3 = new javax.swing.JFormattedTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableSales = new javax.swing.JTable();
        buttonCancel = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        textFieldMovie = new javax.swing.JTextField();
        buttonUpdate = new javax.swing.JButton();
        buttonCleanFilters = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        textFieldInitialValue = new javax.swing.JTextField();
        spinnerInitialDate = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();
        spinnerFinalDate = new javax.swing.JSpinner();
        jLabel5 = new javax.swing.JLabel();
        textFieldFinalValue = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        jFormattedTextField3.setText("jFormattedTextField3");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tableSales.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Filme", "Sessão", "Total", "Hora", "Ingressos Inteiros", "Ingressos Meia"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tableSales);
        if (tableSales.getColumnModel().getColumnCount() > 0) {
            tableSales.getColumnModel().getColumn(1).setPreferredWidth(20);
            tableSales.getColumnModel().getColumn(2).setPreferredWidth(20);
            tableSales.getColumnModel().getColumn(3).setPreferredWidth(40);
            tableSales.getColumnModel().getColumn(4).setPreferredWidth(30);
            tableSales.getColumnModel().getColumn(5).setPreferredWidth(30);
        }

        buttonCancel.setText("Cancelar");
        buttonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCancelActionPerformed(evt);
            }
        });

        jLabel1.setText("Filme:");

        buttonUpdate.setText("Atualizar");
        buttonUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonUpdateActionPerformed(evt);
            }
        });

        buttonCleanFilters.setText("Limpar Filtros");
        buttonCleanFilters.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCleanFiltersActionPerformed(evt);
            }
        });

        jLabel2.setText("Data Inicial:");

        jLabel4.setText("Total Inicial:");

        spinnerInitialDate.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(1510622948989L), null, null, java.util.Calendar.DAY_OF_MONTH));

        jLabel3.setText("Data Final:");

        spinnerFinalDate.setModel(new javax.swing.SpinnerDateModel());

        jLabel5.setText("Total Final:");

        jButton1.setText("Inserir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 755, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buttonCancel))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(spinnerInitialDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(spinnerFinalDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(textFieldInitialValue, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(textFieldFinalValue, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(textFieldMovie))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(buttonUpdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(buttonCleanFilters, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(buttonCleanFilters)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textFieldMovie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonUpdate, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(spinnerInitialDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3)
                        .addComponent(spinnerFinalDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4)
                        .addComponent(textFieldInitialValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5)
                        .addComponent(textFieldFinalValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonCancel)
                    .addComponent(jButton1))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_buttonCancelActionPerformed

    private void buttonCleanFiltersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCleanFiltersActionPerformed
        LocalDate initialDate = LocalDate.now().minusYears(50);
        LocalDate finalDate = LocalDate.now().plusYears(50);
        spinnerInitialDate.setValue(Date.from(initialDate.atStartOfDay
        (ZoneId.systemDefault()).toInstant()));
        spinnerFinalDate.setValue(Date.from(finalDate.atStartOfDay
        (ZoneId.systemDefault()).toInstant()));
        textFieldMovie.setText("");
        textFieldInitialValue.setText("");
        textFieldFinalValue.setText("");
    }//GEN-LAST:event_buttonCleanFiltersActionPerformed

    private void buttonUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonUpdateActionPerformed
        Date initialDate = (Date) spinnerInitialDate.getValue();
        Date finalDate = (Date) spinnerFinalDate.getValue();
        List<Movie> movies = new ArrayList<>();
        if (textFieldMovie.getText() != null && !textFieldMovie.getText().isEmpty()) {
            movies = ReserchUtilities.findMoviesByParams(textFieldMovie.getText(),
                    "Selecione", "Selecione", "Selecione", "    /  /  ", "    /  /  ", null);
        }
        Double initialValue = null;
        Double finalValue = null;
        if (textFieldInitialValue.getText() != null && !textFieldInitialValue.getText().isEmpty()) {
            initialValue = Double.valueOf(textFieldInitialValue.getText());
        }
        if (textFieldFinalValue.getText() != null && !textFieldFinalValue.getText().isEmpty()) {
            finalValue = Double.valueOf(textFieldFinalValue.getText());
        }
        
        fillTable(ReserchUtilities.findSalesByParams(movies, initialDate, finalDate, initialValue, finalValue));
        
    }//GEN-LAST:event_buttonUpdateActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new SaleWindowPanel().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SaleListing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SaleListing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SaleListing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SaleListing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SaleListing().setVisible(true);
            }
        });
    }
    
    private void fillTable(List<Sale> sales) {
        DefaultTableModel defaultTableModel = (DefaultTableModel) tableSales.getModel();

        while (tableSales.getRowCount() > 0) {
            defaultTableModel.removeRow(0);
        }
        
        DateFormat formatter = new SimpleDateFormat("dd/MM/yyyy HH:mm:ss");

        for (Sale sale : sales) {

            Object row[] = new Object[6];
            
            List<Ticket> tickets = sale.getTickets();
            
            List<Ticket> halfTickets = tickets.stream().filter(
                    e->e.getValue() == 8.00).collect(Collectors.toList());
            
            List<Ticket> wholeTickets = tickets.stream().filter(
                    e->e.getValue() == 16.00).collect(Collectors.toList());
            
            row[0] = tickets.get(0).getMovie().getName();
            row[1] = tickets.get(0).getSession().getTime();
            row[2] = sale.getAmount();
            row[3] = formatter.format(sale.getDate());
            row[4] = halfTickets.size();
            row[5] = wholeTickets.size();

            defaultTableModel.addRow(row);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCancel;
    private javax.swing.JButton buttonCleanFilters;
    private javax.swing.JButton buttonUpdate;
    private javax.swing.JButton jButton1;
    private javax.swing.JFormattedTextField jFormattedTextField3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner spinnerFinalDate;
    private javax.swing.JSpinner spinnerInitialDate;
    private javax.swing.JTable tableSales;
    private javax.swing.JTextField textFieldFinalValue;
    private javax.swing.JTextField textFieldInitialValue;
    private javax.swing.JTextField textFieldMovie;
    // End of variables declaration//GEN-END:variables
}
